FIRST_RELEASE = {
    "SUSE Linux Enterprise Server  11": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
    },
    "ALT Linux  7.0.4": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
    },
    "ALT Linux  6.0.1": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
    },
    "ALT Linux  7.0.5": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
    },
    "ALT  8.0": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
    },
    "GosLinux 7.08": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
        'postgrespro-std-9.6': None,
        'postgrespro-ent-9.6': None,
        'postgrespro-ent-10': None,
        'postgrespro-ent-11': None,
    },
    "GosLinux 6.4": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
    },
    "RED OS release MUROM ( 7.1": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
    },
    '"AstraLinuxSE" 1.5': {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
    },
    # astra-smolensk-1.6
    '"AstraLinuxSE" 1.5.28': {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
        'postgrespro-ent-9.6': '9.6.12.1'
    },
    "AlterOS 7.5": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
        'postgrespro-std-9.6': None,
        'postgrespro-std-10': '10.9.1',
        'postgrespro-std-11': '11.4.1',
        'postgrespro-ent-9.6': None,
        'postgrespro-ent-10': '10.9.1',
        'postgrespro-ent-11': '11.4.1',
    },
    "SUSE Linux Enterprise Server  15": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
        'postgrespro-std-9.6': None,
        'postgrespro-std-10': '10.9.1',
        'postgrespro-std-11': '11.4.1',
    },
    "debian 10.0": {
        'postgrespro-std-9.6': '9.6.15.1',
        'postgrespro-std-10': '10.10.1',
        'postgrespro-std-11': '11.5.1',
        'postgrespro-ent-9.6': '9.6.15.1',
        'postgrespro-ent-10': '10.10.1',
        'postgrespro-ent-11': '11.5.1',
    },
    "Ubuntu 19.04": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
        'postgrespro-std-9.6': '9.6.13.1',
        'postgrespro-std-10': '10.9.1',
        'postgrespro-std-11': '11.4.1',
    },
    '"AstraLinuxCE" 2.12.7': {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
        'postgrespro-std-9.6': None,
        'postgrespro-ent-9.6': None,
    },
    "\xd0\x9c\xd0\xa1\xd0\x92\xd0\xa1\xd1\x84\xd0"
    "\xb5\xd1\x80\xd0\xb0  6.3": {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
        'postgrespro-std-9.6': None,
        'postgrespro-std-10': None,
        'postgrespro-std-11': None,
        'postgrespro-ent-9.6': None,
        'postgrespro-ent-10': None,
        'postgrespro-ent-11': None,
    },
    'Red Hat Enterprise Linux 8.0': {
        'postgresql--9.6': None,
        'postgrespro-std-9.6': None,
        'postgrespro-std-10': '10.10.1',
        'postgrespro-std-11': '11.5.1',
        'postgrespro-ent-9.6': None,
        'postgrespro-ent-10': '10.10.1',
        'postgrespro-ent-11': '11.5.1',
    },
    '2012ServerR2 6.3.9600': {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
    },
    '10 10.0.14393': {
        'postgresql--9.6': None,
        'postgresql--10': None,
        'postgresql--11': None,
    },

}
