image: debian

cache:
    untracked: true
    paths:
    - binaries/
    - .config
    - /var/cache/apt/archives

stages:
  - test

before_script:
  - uname -a
  - df -h
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -yqq update
  - apt-get install -yqq python python-dev libyaml-dev python-pip libssl-dev libffi-dev pylint
  - pip install --upgrade cffi
  - pip install ansible-lint
  - pip install pep8

ansible-lint:
  stage: test
  script:
    - ansible-lint static/playbook-prepare-env.yml
  when: always

pep8-check:
  stage: test
  script:
    - pep8 --exclude helpers/datafiller.py --filename=*.py --ignore=W293,E201,E202,E501 --count .
  when: always

pylint-check:
  stage: test
  script:
    - pylint --ignore=datafiller.py -E pg-tests
  when: always
