image: debian

cache:
    untracked: true
    paths:
    - binaries/
    - .config
    - /var/cache/apt/archives

stages:
  - test

before_script:
  - uname -a
  - df -h
  - echo $CI_RUNNER_ID $CI_RUNNER_DESCRIPTION $CI_RUNNER_TAGS
  - export DEBIAN_FRONTEND=noninteractive
  - echo 'do "apt-get -yqq update"' # don't require root to execute this script
  - echo 'do "apt-get install -yqq python python-dev libyaml-dev python-pip libssl-dev libffi-dev pylint python-beautifulsoup"' # don't require root to execute this script
  - pip install setuptools
  - pip install pyasn1
  - pip install cffi
  - pip install ansible-lint
  - pip install pycodestyle
  - pip install psycopg2
  - pip install allure-pytest

ansible-lint:
  stage: test
  script:
    - ansible-lint tests/playbook-prepare-env.yml
    - ansible-lint tests_install/playbook-prepare-env.yml
  when: always

pycodestyle-check:
  stage: test
  script:
    - pycodestyle --exclude helpers/datafiller.py --filename=*.py --ignore=W293,E201,E202,E501 --count .
  when: always

pylint-check:
  stage: test
  script:
    - PYTHONPATH=${PYTHONPATH}:$(dirname %d) pylint --ignore=datafiller.py -E pg-tests
  when: always
