#!/bin/bash

set -e

branch=${1%%/*}
job=${1##*/}
tparts=(${job//-/ })
codename=${tparts[0]}
version=${tparts[1]}

echo $branch
substr1=${job#*-}
os=${substr1#*-}
edn=""
case "$os" in
cert-*)
    os=${os#cert-}
    edn="-cert"
    ;;
*)
    ;;
esac
ext=${os##*-}
case "$ext" in
test)
    os=${os%-test}
    ;;
*)
    ;;
esac

ext=${os##*-}
case "$ext" in
amd64)
    target=${os%-amd64}
    ;;
x86)
    target=${os%-x86}
    ;;
multimaster)
    echo "Invalid project extension ($ext) in $1"
    exit 1
    ;;
*)
    target=$os
    ;;
esac

case "$codename" in
pg1c)
    product="postgrespro"
    edition="1c"
    ;;
pgpro)
    product="postgrespro"
    edition="std$edn"
    ;;
pgproee)
    product="postgrespro"
    edition="ent$edn"
    ;;
*)
    echo "Invalid codename: $codename"
    exit 1
    ;;
esac

case "$codename" in
pgpro | pgproee | pg1c )
    if [ X"$edn" != X"-cert" ]; then
        if [ X"$branch" == X"DEV" ]; then
            extraopt="--product_milestone alpha"
        else
            extraopt="--product_milestone beta"
        fi
    fi
    ;;
esac

sudo chmod -R 777 .
sudo -u tester -i sh -c "cd '$PWD'; ./testrun.py --product_name $product --product_edition $edition --product_version $version --target $target $extraopt --test tests_install/ --clean --export"
